const TOURNAMENT_DATA = {
    settings: {
        startTime: "07:30",
        halfMinutes: 6,
        gapMinutes: 0
    },

    players: [
        ["Prakul Mishra", "MBATM25025"],
        ["Tushar Singh", "MBA25181"],
        ["Shubham Kashyap", "MBA25140"],
        ["Adhyan Kumar", "MBA25231"],
        ["Aryaman Singh", "MBA25059"],
        ["Nima", "MBA25075"],
        ["Robert Gupta", "mba25083"],
        ["PARIMAL MISHRA", "mba25171"],
        ["Anirban Guha", "MBA26008"],
        ["Rieshi Rao", "MBA26049"],
        ["Shubh Wadhwa", "MBA26120"],
        ["Karanbir Singh Dhoul", "MBA26158"],
        ["Abhilash Naskar", "MBA26004"],
        ["Siddhant Singh", "MBA25180"],
        ["Kush Soni", "MBA25119"],
        ["Jay Mishra", "MBATm26037"],
        ["Hemant Agrawal", "mba25188"],
        ["Varun Rathi", "MBA25230"],
        ["kartikay sharma", "mbatm26016"],
        ["Meet Gowsawmi", "25001"],
        ["Rehan Malik", ""],
        ["Chaitanya Wankhande", "25002"],
        ["RajVardhan", "25003"],
        ["Hodor", "25004"],
        ["Arush", "25005"]
    ],

    matches: [
        {
            id: "p1",
            stage: "prelim",
            p1: "Anirban Guha",
            p2: "Robert Gupta",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "r1",
            nextSlot: 1,
            bye: false
        },
        {
            id: "p2",
            stage: "prelim",
            p1: "Prakul Mishra",
            p2: "RajVardhan",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "r2",
            nextSlot: 1,
            bye: false
        },
        {
            id: "p3",
            stage: "prelim",
            p1: "Abhilash Naskar",
            p2: "Hodor",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "r3",
            nextSlot: 1,
            bye: false
        },
        {
            id: "p4",
            stage: "prelim",
            p1: "Karanbir Singh Dhoul",
            p2: "Rieshi Rao",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "r4",
            nextSlot: 1,
            bye: false
        },
        {
            id: "p5",
            stage: "prelim",
            p1: "Meet Gowsawmi",
            p2: "Adhyan Kumar",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "r5",
            nextSlot: 1,
            bye: false
        },
        {
            id: "p6",
            stage: "prelim",
            p1: "Chaitanya Wankhande",
            p2: "Shubh Wadhwa",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "r6",
            nextSlot: 1,
            bye: false
        },
        {
            id: "p7",
            stage: "prelim",
            p1: "Jay Mishra",
            p2: "kartikay sharma",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "r7",
            nextSlot: 1,
            bye: false
        },
        {
            id: "p8",
            stage: "prelim",
            p1: "Nima",
            p2: "Arush",
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: null,
            nextSlot: null,
            bye: false
        },

        {
            id: "r1",
            stage: "r16",
            p1: "Kush Soni",
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "q1",
            nextSlot: 0,
            bye: false
        },
        {
            id: "r2",
            stage: "r16",
            p1: "PARIMAL MISHRA",
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "q1",
            nextSlot: 1,
            bye: false
        },
        {
            id: "r3",
            stage: "r16",
            p1: "Siddhant Singh",
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "q2",
            nextSlot: 0,
            bye: false
        },
        {
            id: "r4",
            stage: "r16",
            p1: "Tushar Singh",
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "q2",
            nextSlot: 1,
            bye: false
        },
        {
            id: "r5",
            stage: "r16",
            p1: "Aryaman Singh",
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "q3",
            nextSlot: 0,
            bye: false
        },
        {
            id: "r6",
            stage: "r16",
            p1: "Hemant Agrawal",
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "q3",
            nextSlot: 1,
            bye: false
        },
        {
            id: "r7",
            stage: "r16",
            p1: "Shubham Kashyap",
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "q4",
            nextSlot: 0,
            bye: false
        },
        {
            id: "r8",
            stage: "r16",
            p1: "Varun Rathi",
            p2: null,
            score1: null,
            score2: null,
            winner: "Varun Rathi",
            penalties: null,
            nextMatch: "q4",
            nextSlot: 1,
            bye: true
        },

        {
            id: "q1",
            stage: "qf",
            p1: null,
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "s1",
            nextSlot: 0,
            bye: false
        },
        {
            id: "q2",
            stage: "qf",
            p1: null,
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "s1",
            nextSlot: 1,
            bye: false
        },
        {
            id: "q3",
            stage: "qf",
            p1: null,
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "s2",
            nextSlot: 0,
            bye: false
        },
        {
            id: "q4",
            stage: "qf",
            p1: null,
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "s2",
            nextSlot: 1,
            bye: false
        },

        {
            id: "s1",
            stage: "sf",
            p1: null,
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "f1",
            nextSlot: 0,
            bye: false
        },
        {
            id: "s2",
            stage: "sf",
            p1: null,
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: "f1",
            nextSlot: 1,
            bye: false
        },

        {
            id: "f1",
            stage: "final",
            p1: null,
            p2: null,
            score1: null,
            score2: null,
            winner: null,
            penalties: null,
            nextMatch: null,
            nextSlot: null,
            bye: false
        }
    ]
};
